title: "Bernhard Ulrich von Boyen"
description: "Actuarial intelligence, cross-domain analytics, projects with integrity & AI"
url: "https://bvonboyen.github.io"
baseurl: ""
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
search: true


paginate: 5              # Anzahl Posts pro Seite
paginate_path: "/page:num/"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate


author:
  name: "Bernhard von Boyen"

email: "bernhard.vonboyen@gmail.com"
github_username: bvonboyen
linkedin_username: bernhard-von-boyen-ba56042

collections:
  projects:
    output: true
    permalink: /projects/:name/
